FROM python:3
USER root

# Create a working directory
RUN mkdir /app
WORKDIR /app
RUN chmod 777 /app

# Install python packages from requirements file
RUN python -m pip install --upgrade pip
ADD requirements.txt /app/
RUN pip install -r /app/requirements.txt

ADD . /app/
RUN which python \
 && export PYTHONPATH=.

WORKDIR /app
RUN chmod 755 /app/scripts/server.sh